#!/usr/bin/env node
// Design-system integrity check.
//
// The bundle (_ds_bundle.js) and manifest (_ds_manifest.json) are generated by
// the design tool — the linked project is the source of truth. CI does NOT
// rebuild them; it only verifies that what was exported into this mirror is
// internally consistent: declared structure, tokens, fonts and manifest refs
// all resolve on disk. Exits non-zero on the first broken contract.

import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const r = (p) => join(root, p);

const errors = [];
const checks = [];
const fail = (msg) => errors.push(msg);
const ok = (msg) => checks.push(msg);

const need = (p, label) => {
  if (existsSync(r(p))) ok(`${label}: ${p}`);
  else fail(`${label} missing: ${p}`);
};

// ---- config ----
let config;
try {
  config = JSON.parse(readFileSync(r('.design-sync/config.json'), 'utf8'));
  ok('config.json parsed');
} catch (e) {
  console.error('✗ cannot read .design-sync/config.json —', e.message);
  process.exit(1);
}

// ---- 1. structure: declared entry points ----
need(config.cssEntry, 'css entry');
need(config.bundle, 'bundle');
need(config.manifest, 'manifest');
need(config.adherence, 'adherence config');

// ---- 2. tokens ----
const tokensDir = (config.tokensGlob || 'tokens/*.css').split('/')[0];
let tokenFiles = [];
try {
  tokenFiles = readdirSync(r(tokensDir)).filter((f) => f.endsWith('.css'));
} catch { /* handled below */ }
if (tokenFiles.length) ok(`tokens: ${tokenFiles.length} css files in ${tokensDir}/`);
else fail(`tokens: no .css files found in ${tokensDir}/`);

// ---- 3. fonts (css + webfont assets) ----
for (const f of config.fonts || []) need(f, 'font css');
for (const a of config.fontAssets || []) need(a, 'font asset');

// ---- 4. manifest integrity ----
let manifest;
try {
  manifest = JSON.parse(readFileSync(r(config.manifest), 'utf8'));
} catch (e) {
  fail(`manifest unparseable: ${e.message}`);
}

if (manifest) {
  if (manifest.namespace === config.namespace) ok(`namespace matches: ${config.namespace}`);
  else fail(`namespace mismatch: manifest=${manifest.namespace} config=${config.namespace}`);

  const refs = [
    ...(manifest.components || []).map((c) => ['component', c.name, c.sourcePath]),
    ...(manifest.cards || []).map((c) => ['card', c.name, c.path || c.sourcePath]),
    ...(manifest.globalCssPaths || []).map((p) => ['globalCss', p, p]),
  ];
  const broken = refs.filter(([, , p]) => p && !existsSync(r(p)));
  const total = refs.filter(([, , p]) => p).length;
  if (broken.length === 0) ok(`manifest refs resolve: ${total} (components/cards/globalCss)`);
  else broken.forEach(([kind, name, p]) => fail(`${kind} "${name}" → missing ${p}`));

  // font files declared inside the manifest
  for (const font of manifest.fonts || []) {
    if (font.cssPath) need(font.cssPath, `font "${font.family}" css`);
    for (const file of font.files || []) need(file, `font "${font.family}" file`);
  }
}

// ---- report ----
for (const c of checks) console.log(`✓ ${c}`);
if (errors.length) {
  console.error(`\n✗ ${errors.length} integrity error(s):`);
  for (const e of errors) console.error(`  - ${e}`);
  process.exit(1);
}
console.log(`\n✓ Design system integrity OK — ${checks.length} checks passed.`);
